# Use Open AI with key
provider: autogen_ext.models.openai.OpenAIChatCompletionClient
config:
  model: gemini-2.0-flash-lite
  api_key: AIzaSyB45FYaepy06XwOuk6xd6KoeKrwZsV9qOE
  base_url: https://generativelanguage.googleapis.com/v1beta/openai/
  model_info:
    vision: true
    function_calling: true
    json_output: true
    family: "unknown"
    structured_output: true